### ISSUE TITLE
Deploy/connect Ethereum Hello Zuidhorn service

### ISSUE THREAD

**Issue by jastam** [teamforus/rd-hello-world-eth#5]
- [x] Automatically deploy a smart contract in a Geth docker container;
- [x] Get the Hello World API on Docker store

**Comment by jastam** [comment]
Geth docker image is available at: jastam/geth. This one uses POA with a fixed blocktime of 5 seconds.

Start: docker run -d --name geth -p 8546:8546 jastam/geth
Stop: docker stop geth
Restart: docker start geth
Attach (from host): geth attach ws://127.0.0.1:8546

**Comment by martijndoornik** [comment]
Dude! How did you get this working? What was wrong?

I'll test it right away

**Comment by jastam** [comment]
I guess something was wrong with the build. I did a rebuilt to test something else and the connection started working as well. I didn't change anything related to it.

**Comment by maxvisser** [comment]
you did change the wsaddr to 0.0.0.0 right?

**Comment by martijndoornik** [comment]
@jastam 

Got this error with another image as well. Got any help for this?

docker: Error response from daemon: driver failed programming external connectivity on endpoint geth (c52252ba682476b15124b2bf3a684ffa7ed041182841a288090b20da33dbc36c): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8546:tcp:172.17.0.3:8546: input/output error.

**Comment by jastam** [comment]
@maxvisser I did
@martijndoornik  Can the port be in used by another program running on the host or another running container?

**Comment by martijndoornik** [comment]
In the API, the Hello World is available. I will look into automatically deploying a contract in @jastam 's docker container with POA-Geth and how to geth the dockerfile on Docker Store.

- [ ] Automatically deploy a smart contract in a Geth docker container;

- [ ] Get the Hello World API on Docker store

**Comment by martijndoornik** [comment]
Available as martijndoornik/io.forus.api.eth on hub.docker.io
