### ISSUE TITLE
change name to rd-eth-hello-world or other name

### ISSUE THREAD

**Issue by maxvisser** [teamforus/rd-hello-world-eth#9]
This is not directly involved with the current development of forus. Please change the name.

https://github.com/teamforus/organisation-internal/issues/16

**Comment by martijndoornik** [comment]
Renamed to rd-hello-world-eth, meaning it is in domain r&d, project hello-world, implementation of eth. Might change it to rd.hello-world.eth, depending on how the rest feels about this.
